!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  bool_param: true
  double_param: 0.5
  fun_type: 1
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      bool_param: true
      double_param: 0.5
      fun_type: 1
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      int_param: 50
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      str_param: Hello World
      type: ''
    state: []
  int_param: 50
  str_param: Hello World
state: []
